"""added subscription and api key

Revision ID: 3879bdbfbb6a
Revises: 40e607b1a44a
Create Date: 2025-01-12 13:38:55.255059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3879bdbfbb6a'
down_revision: Union[str, None] = '40e607b1a44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
