"""added linkedin colun for user

Revision ID: 40e607b1a44a
Revises: 77e6a9448e4d
Create Date: 2024-10-05 11:26:01.372141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e607b1a44a'
down_revision: Union[str, None] = '77e6a9448e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_address')
    # ### end Alembic commands ###
